{% set version = "1.84" %}

package:
  name: surelog
  version: {{ version }}

source:
  url: https://github.com/chipsalliance/surelog/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ddcbc0d943ee52f2487b7a064c57a8239d525efd9a45b1f3e3e4a96a56cb3377

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('surelog', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - antlr
    - antlr-cpp-runtime
    - capnproto
    - nlohmann_json
    - uhdm ={{ version }}
    - zlib
    # Embeds a python interpreter
    - python
    - swig
    - orderedmultidict
  run:
    - antlr-cpp-runtime
    - capnproto
    - uhdm ={{ version }}
    - python

test:
  commands:
    - test -f $PREFIX/bin/surelog

about:
  home: https://github.com/chipsalliance/Surelog
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SystemVerilog 2017 Pre-processor, Parser, Elaborator, UHDM Compiler. Provides IEEE Design/TB C/C++ VPI and Python AST & UHDM APIs. Compiles on Linux gcc, Windows msys2-gcc & msvc, OsX
  description: |
    SystemVerilog 2017 Pre-processor, Parser, Elaborator, UHDM Compiler. Provides IEEE Design/TB C/C++ VPI and Python AST & UHDM APIs. Compiles on Linux gcc, Windows msys2-gcc & msvc, OsX
  dev_url: https://github.com/chipsalliance/Surelog

extra:
  recipe-maintainers:
    - timkpaine
